USE cars

DROP TABLE IF EXISTS cars;

CREATE TABLE cars(Id INTEGER PRIMARY KEY, Name TEXT, Price INTEGER);
INSERT INTO cars VALUES(1, 'Audi', 52642);
INSERT INTO cars VALUES(2, 'Mercedes', 57127);
INSERT INTO cars VALUES(3, 'Skoda', 9000);
INSERT INTO cars VALUES(4, 'Volvo', 29000);
INSERT INTO cars VALUES(5, 'Bentley', 350000);
INSERT INTO cars VALUES(6, 'Citroen', 21000);
INSERT INTO cars VALUES(7, 'Hummer', 41400);
INSERT INTO cars VALUES(8, 'Volkswagen', 21600);
COMMIT;

