version: '2'

services:

    flaskapi:
        build: .
        image: flaskapi
        ports:
            - "5000:5000"
        stop_signal: SIGINT
        environment:
            - db_user=root
            - db_passowrd=Passw0rd!
            - db_address=192.168.192.16
            - db_port=3306
